### ISSUE TITLE
Elevation of location has no influence on sunrise and sunset times

### ISSUE THREAD

**Issue by jonas-hagen** [sffjunkie/astral#15]
At a higher elevation (meters above sea level) the sun rises earlier than at lower elevations. This is not implemented in astral 1.6, even though the Location class has an elevation attribute.

``` Python console
>>> import astral
>>> low = astral.Location(('A', 'B', 46.95, 7.47, 'UTC', 500))
>>> low.sun()['sunrise']
datetime.datetime(2018, 3, 12, 5, 49, 47, tzinfo=<UTC>)
>>> high = astral.Location(('A', 'B', 46.95, 7.47, 'UTC', 4000))
>>> high.sun()['sunrise']
datetime.datetime(2018, 3, 12, 5, 49, 47, tzinfo=<UTC>)
```

**Comment by sffjunkie** [comment]
The change in times due to elevation has been implemented in 1.9.1
See the docs at https://astral.readthedocs.io/en/stable/#effect-of-elevation for details on how the adjustment is calculated.
I'm not totally sure I've used the correct calc for the adjustment so if you have any comments let me know.
